# Build
FROM node:20-alpine AS builder
WORKDIR /app

# copy package files
COPY frontend/package*.json ./frontend/
COPY shared/package*.json ./shared/

# install
WORKDIR /app/frontend
RUN npm install --legacy-peer-deps

# copy source code
WORKDIR /app
COPY shared/ ./shared/
COPY frontend/ ./frontend/

# build frontend
WORKDIR /app/frontend
RUN npm run build

# Serve
FROM nginx:stable-alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]