# Build
FROM node:20-alpine AS builder
WORKDIR /app

# copy package files
COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/

# install
WORKDIR /app/backend
RUN npm install --legacy-peer-deps

# copy source code
WORKDIR /app
COPY shared/ ./shared/
COPY backend/ ./backend/

# build backend
WORKDIR /app/backend
RUN npm run build

# Run (new image)
FROM node:20-alpine
WORKDIR /app

# copy files from first build
COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/backend/node_modules ./node_modules
COPY --from=builder /app/backend/package.json ./package.json

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/backend/src/main.js"]